# Generated by Django 4.2 on 2023-05-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPNAME', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='val',
            field=models.CharField(default='-', max_length=300),
        ),
    ]
