# Generated by Django 4.2.3 on 2023-07-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPNAME', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='val',
            field=models.CharField(default='-', max_length=300, unique=True),
        ),
    ]
