# Generated by Django 4.2 on 2023-05-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPNAME', '0002_password_val'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='val',
            field=models.CharField(default='-', max_length=300, unique=True),
        ),
    ]
